from PyQt5 import QtCore, QtGui, QtWidgets
from sudoku_solver import Sudoku
import re
import random


class UiMainWindow(object):
    def __init__(self):
        self.MainWindow = QtWidgets.QMainWindow()
        self.actionSave = QtWidgets.QAction(self.MainWindow)
        self.menubar = QtWidgets.QMenuBar(self.MainWindow)
        self.menuHallo = QtWidgets.QMenu(self.menubar)
        self.centralwidget = QtWidgets.QWidget(self.MainWindow)
        self.i0_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.actionOpen = QtWidgets.QAction(self.MainWindow)
        self.actionNew = QtWidgets.QAction(self.MainWindow)
        self.statusbar = QtWidgets.QStatusBar(self.MainWindow)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.tipp_bttn = QtWidgets.QPushButton(self.centralwidget)
        self.solve_bttn = QtWidgets.QPushButton(self.centralwidget)
        self.validate_bttn = QtWidgets.QPushButton(self.centralwidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)

        self.i4_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.i8_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.i1_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.i8_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.i6_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.i2_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.i7_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.i2_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.i5_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.i2_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.i4_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.i0_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.i6_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.i8_0 = QtWidgets.QTextEdit(self.centralwidget)
        self.i4_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.i1_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.i8_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.i6_0 = QtWidgets.QTextEdit(self.centralwidget)
        self.i2_0 = QtWidgets.QTextEdit(self.centralwidget)
        self.i0_0 = QtWidgets.QTextEdit(self.centralwidget)
        self.i4_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.i6_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.i5_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.i4_0 = QtWidgets.QTextEdit(self.centralwidget)
        self.i3_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.i7_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.i1_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.i2_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.i5_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.i7_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.i0_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.i7_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.i8_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.i6_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.i1_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.i5_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.i8_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.i3_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.i1_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.i0_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.i4_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.i3_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.i3_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.i0_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.i6_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.i3_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.i6_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.i8_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.i1_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.i5_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.i8_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.i7_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.i6_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.i4_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.i2_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.i0_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.i3_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.i0_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.i7_0 = QtWidgets.QTextEdit(self.centralwidget)
        self.i3_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.i5_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.i2_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.i4_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.i1_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.i4_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.i5_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.i1_0 = QtWidgets.QTextEdit(self.centralwidget)
        self.i7_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.i5_0 = QtWidgets.QTextEdit(self.centralwidget)
        self.i1_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.i7_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.i3_0 = QtWidgets.QTextEdit(self.centralwidget)
        self.i2_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.i3_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.i2_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.i5_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.i0_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.i8_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.i6_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.i7_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)

        self.setupUi()
        self.MainWindow.show()

        self.elements = [
            [self.i0_0, self.i1_0, self.i2_0, self.i3_0, self.i4_0, self.i5_0, self.i6_0, self.i7_0, self.i8_0],
            [self.i0_1, self.i1_1, self.i2_1, self.i3_1, self.i4_1, self.i5_1, self.i6_1, self.i7_1, self.i8_1],
            [self.i0_2, self.i1_2, self.i2_2, self.i3_2, self.i4_2, self.i5_2, self.i6_2, self.i7_2, self.i8_2],
            [self.i0_3, self.i1_3, self.i2_3, self.i3_3, self.i4_3, self.i5_3, self.i6_3, self.i7_3, self.i8_3],
            [self.i0_4, self.i1_4, self.i2_4, self.i3_4, self.i4_4, self.i5_4, self.i6_4, self.i7_4, self.i8_4],
            [self.i0_5, self.i1_5, self.i2_5, self.i3_5, self.i4_5, self.i5_5, self.i6_5, self.i7_5, self.i8_5],
            [self.i0_6, self.i1_6, self.i2_6, self.i3_6, self.i4_6, self.i5_6, self.i6_6, self.i7_6, self.i8_6],
            [self.i0_7, self.i1_7, self.i2_7, self.i3_7, self.i4_7, self.i5_7, self.i6_7, self.i7_7, self.i8_7],
            [self.i0_8, self.i1_8, self.i2_8, self.i3_8, self.i4_8, self.i5_8, self.i6_8, self.i7_8, self.i8_8]
        ]
        self.elements_dict = {
            self.i0_0: "", self.i1_0: "", self.i2_0: "", self.i3_0: "", self.i4_0: "", self.i5_0: "", self.i6_0: "", self.i7_0: "", self.i8_0: "",
            self.i0_1: "", self.i1_1: "", self.i2_1: "", self.i3_1: "", self.i4_1: "", self.i5_1: "", self.i6_1: "", self.i7_1: "", self.i8_1: "",
            self.i0_2: "", self.i1_2: "", self.i2_2: "", self.i3_2: "", self.i4_2: "", self.i5_2: "", self.i6_2: "", self.i7_2: "", self.i8_2: "",
            self.i0_3: "", self.i1_3: "", self.i2_3: "", self.i3_3: "", self.i4_3: "", self.i5_3: "", self.i6_3: "", self.i7_3: "", self.i8_3: "",
            self.i0_4: "", self.i1_4: "", self.i2_4: "", self.i3_4: "", self.i4_4: "", self.i5_4: "", self.i6_4: "", self.i7_4: "", self.i8_4: "",
            self.i0_5: "", self.i1_5: "", self.i2_5: "", self.i3_5: "", self.i4_5: "", self.i5_5: "", self.i6_5: "", self.i7_5: "", self.i8_5: "",
            self.i0_6: "", self.i1_6: "", self.i2_6: "", self.i3_6: "", self.i4_6: "", self.i5_6: "", self.i6_6: "", self.i7_6: "", self.i8_6: "",
            self.i0_7: "", self.i1_7: "", self.i2_7: "", self.i3_7: "", self.i4_7: "", self.i5_7: "", self.i6_7: "", self.i7_7: "", self.i8_7: "",
            self.i0_8: "", self.i1_8: "", self.i2_8: "", self.i3_8: "", self.i4_8: "", self.i5_8: "", self.i6_8: "", self.i7_8: "", self.i8_8: ""
        }
        self.addValidator()

    def addValidator(self):
        # For every TextEdit, add a validator function that checks for valid input
        for y in self.elements:
            for x in y:
                x.textChanged.connect(lambda x0=x: self.textChangedEvent(x0))

    def textChangedEvent(self, elem: QtWidgets.QTextEdit):
        # On every input to the TextEdit, check if it's valid
        pattern = re.compile(r"(^[1-9]\Z)|(^\Z)")  # Pattern for detecting valid inputs
        text = elem.toPlainText()  # Retrieve the inputed text
        if not pattern.search(text):  # If the input isn't valid
            if len(text) == 2 and pattern.search(text[1]):  # If cell already has an input but another one is inputed: Accept the newer one
                elem.setText(text[1])
                self.elements_dict[elem] = text[1]  # Change the before cached input
            else:
                elem.setText(self.elements_dict[elem])  # If not set the old input
        else:
            self.elements_dict[elem] = text  # Change the before cached input
        cursor = elem.textCursor()
        cursor.movePosition(QtGui.QTextCursor.End)
        elem.setTextCursor(cursor)

    def setupUi(self):
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.resize(725, 822)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.setObjectName("gridLayout")
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i2_8.setFont(font)
        self.i2_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i2_8.setObjectName("i2_8")
        self.gridLayout.addWidget(self.i2_8, 10, 2, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i7_8.setFont(font)
        self.i7_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i7_8.setObjectName("i7_8")
        self.gridLayout.addWidget(self.i7_8, 10, 9, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i6_8.setFont(font)
        self.i6_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i6_8.setObjectName("i6_8")
        self.gridLayout.addWidget(self.i6_8, 10, 8, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i8_8.setFont(font)
        self.i8_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i8_8.setObjectName("i8_8")
        self.gridLayout.addWidget(self.i8_8, 10, 10, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i4_6.setFont(font)
        self.i4_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i4_6.setObjectName("i4_6")
        self.gridLayout.addWidget(self.i4_6, 8, 5, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i0_7.setFont(font)
        self.i0_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i0_7.setObjectName("i0_7")
        self.gridLayout.addWidget(self.i0_7, 9, 0, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i5_6.setFont(font)
        self.i5_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i5_6.setObjectName("i5_6")
        self.gridLayout.addWidget(self.i5_6, 8, 6, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i2_6.setFont(font)
        self.i2_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i2_6.setObjectName("i2_6")
        self.gridLayout.addWidget(self.i2_6, 8, 2, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i3_8.setFont(font)
        self.i3_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i3_8.setObjectName("i3_8")
        self.gridLayout.addWidget(self.i3_8, 10, 4, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i3_0.setFont(font)
        self.i3_0.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i3_0.setObjectName("i3_0")
        self.gridLayout.addWidget(self.i3_0, 0, 4, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i7_1.setFont(font)
        self.i7_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i7_1.setObjectName("i7_1")
        self.gridLayout.addWidget(self.i7_1, 1, 9, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i1_1.setFont(font)
        self.i1_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i1_1.setObjectName("i1_1")
        self.gridLayout.addWidget(self.i1_1, 1, 1, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i5_0.setFont(font)
        self.i5_0.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i5_0.setObjectName("i5_0")
        self.gridLayout.addWidget(self.i5_0, 0, 6, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i1_0.setFont(font)
        self.i1_0.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i1_0.setObjectName("i1_0")
        self.gridLayout.addWidget(self.i1_0, 0, 1, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i7_7.setFont(font)
        self.i7_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i7_7.setObjectName("i7_7")
        self.gridLayout.addWidget(self.i7_7, 9, 9, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i0_8.setFont(font)
        self.i0_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i0_8.setObjectName("i0_8")
        self.gridLayout.addWidget(self.i0_8, 10, 0, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i5_8.setFont(font)
        self.i5_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i5_8.setObjectName("i5_8")
        self.gridLayout.addWidget(self.i5_8, 10, 6, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i1_8.setFont(font)
        self.i1_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i1_8.setObjectName("i1_8")
        self.gridLayout.addWidget(self.i1_8, 10, 1, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i4_8.setFont(font)
        self.i4_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i4_8.setObjectName("i4_8")
        self.gridLayout.addWidget(self.i4_8, 10, 5, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i2_2.setFont(font)
        self.i2_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i2_2.setObjectName("i2_2")
        self.gridLayout.addWidget(self.i2_2, 2, 2, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i0_2.setFont(font)
        self.i0_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i0_2.setObjectName("i0_2")
        self.gridLayout.addWidget(self.i0_2, 2, 0, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i5_1.setFont(font)
        self.i5_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i5_1.setObjectName("i5_1")
        self.gridLayout.addWidget(self.i5_1, 1, 6, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i3_1.setFont(font)
        self.i3_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i3_1.setObjectName("i3_1")
        self.gridLayout.addWidget(self.i3_1, 1, 4, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i7_0.setFont(font)
        self.i7_0.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i7_0.setObjectName("i7_0")
        self.gridLayout.addWidget(self.i7_0, 0, 9, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i3_2.setFont(font)
        self.i3_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i3_2.setObjectName("i3_2")
        self.gridLayout.addWidget(self.i3_2, 2, 4, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i0_1.setFont(font)
        self.i0_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i0_1.setObjectName("i0_1")
        self.gridLayout.addWidget(self.i0_1, 1, 0, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i3_4.setFont(font)
        self.i3_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i3_4.setObjectName("i3_4")
        self.gridLayout.addWidget(self.i3_4, 5, 4, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i2_5.setFont(font)
        self.i2_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i2_5.setObjectName("i2_5")
        self.gridLayout.addWidget(self.i2_5, 6, 2, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i4_3.setFont(font)
        self.i4_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i4_3.setObjectName("i4_3")
        self.gridLayout.addWidget(self.i4_3, 4, 5, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i6_3.setFont(font)
        self.i6_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i6_3.setObjectName("i6_3")
        self.gridLayout.addWidget(self.i6_3, 4, 8, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i7_5.setFont(font)
        self.i7_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i7_5.setObjectName("i7_5")
        self.gridLayout.addWidget(self.i7_5, 6, 9, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i8_5.setFont(font)
        self.i8_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i8_5.setObjectName("i8_5")
        self.gridLayout.addWidget(self.i8_5, 6, 10, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i5_5.setFont(font)
        self.i5_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i5_5.setObjectName("i5_5")
        self.gridLayout.addWidget(self.i5_5, 6, 6, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i1_4.setFont(font)
        self.i1_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i1_4.setObjectName("i1_4")
        self.gridLayout.addWidget(self.i1_4, 5, 1, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i8_3.setFont(font)
        self.i8_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i8_3.setObjectName("i8_3")
        self.gridLayout.addWidget(self.i8_3, 4, 10, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i6_6.setFont(font)
        self.i6_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i6_6.setObjectName("i6_6")
        self.gridLayout.addWidget(self.i6_6, 8, 8, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i3_6.setFont(font)
        self.i3_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i3_6.setObjectName("i3_6")
        self.gridLayout.addWidget(self.i3_6, 8, 4, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i6_5.setFont(font)
        self.i6_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i6_5.setObjectName("i6_5")
        self.gridLayout.addWidget(self.i6_5, 6, 8, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i0_5.setFont(font)
        self.i0_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i0_5.setObjectName("i0_5")
        self.gridLayout.addWidget(self.i0_5, 6, 0, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i3_5.setFont(font)
        self.i3_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i3_5.setObjectName("i3_5")
        self.gridLayout.addWidget(self.i3_5, 6, 4, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i4_5.setFont(font)
        self.i4_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i4_5.setObjectName("i4_5")
        self.gridLayout.addWidget(self.i4_5, 6, 5, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i0_6.setFont(font)
        self.i0_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i0_6.setObjectName("i0_6")
        self.gridLayout.addWidget(self.i0_6, 8, 0, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i1_6.setFont(font)
        self.i1_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i1_6.setObjectName("i1_6")
        self.gridLayout.addWidget(self.i1_6, 8, 1, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i6_7.setFont(font)
        self.i6_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i6_7.setObjectName("i6_7")
        self.gridLayout.addWidget(self.i6_7, 9, 8, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i3_7.setFont(font)
        self.i3_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i3_7.setObjectName("i3_7")
        self.gridLayout.addWidget(self.i3_7, 9, 4, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i8_6.setFont(font)
        self.i8_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i8_6.setObjectName("i8_6")
        self.gridLayout.addWidget(self.i8_6, 8, 10, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i5_7.setFont(font)
        self.i5_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i5_7.setObjectName("i5_7")
        self.gridLayout.addWidget(self.i5_7, 9, 6, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i1_7.setFont(font)
        self.i1_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i1_7.setObjectName("i1_7")
        self.gridLayout.addWidget(self.i1_7, 9, 1, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i8_7.setFont(font)
        self.i8_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i8_7.setObjectName("i8_7")
        self.gridLayout.addWidget(self.i8_7, 9, 10, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i7_6.setFont(font)
        self.i7_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i7_6.setObjectName("i7_6")
        self.gridLayout.addWidget(self.i7_6, 8, 9, 1, 1)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 7, 4, 1, 3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 7, 8, 1, 3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i0_3.setFont(font)
        self.i0_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i0_3.setObjectName("i0_3")
        self.gridLayout.addWidget(self.i0_3, 4, 0, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i7_4.setFont(font)
        self.i7_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i7_4.setObjectName("i7_4")
        self.gridLayout.addWidget(self.i7_4, 5, 9, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i7_2.setFont(font)
        self.i7_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i7_2.setObjectName("i7_2")
        self.gridLayout.addWidget(self.i7_2, 2, 9, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i5_4.setFont(font)
        self.i5_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i5_4.setObjectName("i5_4")
        self.gridLayout.addWidget(self.i5_4, 5, 6, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i2_3.setFont(font)
        self.i2_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i2_3.setObjectName("i2_3")
        self.gridLayout.addWidget(self.i2_3, 4, 2, 1, 1)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 7, 0, 1, 3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i1_5.setFont(font)
        self.i1_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i1_5.setObjectName("i1_5")
        self.gridLayout.addWidget(self.i1_5, 6, 1, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i5_3.setFont(font)
        self.i5_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i5_3.setObjectName("i5_3")
        self.gridLayout.addWidget(self.i5_3, 4, 6, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i3_3.setFont(font)
        self.i3_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i3_3.setObjectName("i3_3")
        self.gridLayout.addWidget(self.i3_3, 4, 4, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i4_0.setFont(font)
        self.i4_0.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i4_0.setObjectName("i4_0")
        self.gridLayout.addWidget(self.i4_0, 0, 5, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i6_2.setFont(font)
        self.i6_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i6_2.setObjectName("i6_2")
        self.gridLayout.addWidget(self.i6_2, 2, 8, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i4_2.setFont(font)
        self.i4_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i4_2.setObjectName("i4_2")
        self.gridLayout.addWidget(self.i4_2, 2, 5, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i0_0.setFont(font)
        self.i0_0.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i0_0.setObjectName("i0_0")
        self.gridLayout.addWidget(self.i0_0, 0, 0, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i8_2.setFont(font)
        self.i8_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i8_2.setObjectName("i8_2")
        self.gridLayout.addWidget(self.i8_2, 2, 10, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i2_0.setFont(font)
        self.i2_0.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i2_0.setObjectName("i2_0")
        self.gridLayout.addWidget(self.i2_0, 0, 2, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i6_0.setFont(font)
        self.i6_0.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i6_0.setObjectName("i6_0")
        self.gridLayout.addWidget(self.i6_0, 0, 8, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i1_3.setFont(font)
        self.i1_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i1_3.setObjectName("i1_3")
        self.gridLayout.addWidget(self.i1_3, 4, 1, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i6_1.setFont(font)
        self.i6_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i6_1.setObjectName("i6_1")
        self.gridLayout.addWidget(self.i6_1, 1, 8, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i4_1.setFont(font)
        self.i4_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i4_1.setObjectName("i4_1")
        self.gridLayout.addWidget(self.i4_1, 1, 5, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i8_0.setFont(font)
        self.i8_0.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i8_0.setObjectName("i8_0")
        self.gridLayout.addWidget(self.i8_0, 0, 10, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i5_2.setFont(font)
        self.i5_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i5_2.setObjectName("i5_2")
        self.gridLayout.addWidget(self.i5_2, 2, 6, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i0_4.setFont(font)
        self.i0_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i0_4.setObjectName("i0_4")
        self.gridLayout.addWidget(self.i0_4, 5, 0, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i4_4.setFont(font)
        self.i4_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i4_4.setObjectName("i4_4")
        self.gridLayout.addWidget(self.i4_4, 5, 5, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i2_4.setFont(font)
        self.i2_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i2_4.setObjectName("i2_4")
        self.gridLayout.addWidget(self.i2_4, 5, 2, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i2_7.setFont(font)
        self.i2_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i2_7.setObjectName("i2_7")
        self.gridLayout.addWidget(self.i2_7, 9, 2, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i7_3.setFont(font)
        self.i7_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i7_3.setObjectName("i7_3")
        self.gridLayout.addWidget(self.i7_3, 4, 9, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i8_4.setFont(font)
        self.i8_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i8_4.setObjectName("i8_4")
        self.gridLayout.addWidget(self.i8_4, 5, 10, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i2_1.setFont(font)
        self.i2_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i2_1.setObjectName("i2_1")
        self.gridLayout.addWidget(self.i2_1, 1, 2, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i6_4.setFont(font)
        self.i6_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i6_4.setObjectName("i6_4")
        self.gridLayout.addWidget(self.i6_4, 5, 8, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i8_1.setFont(font)
        self.i8_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i8_1.setObjectName("i8_1")
        self.gridLayout.addWidget(self.i8_1, 1, 10, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i1_2.setFont(font)
        self.i1_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i1_2.setObjectName("i1_2")
        self.gridLayout.addWidget(self.i1_2, 2, 1, 1, 1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.i4_7.setFont(font)
        self.i4_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.i4_7.setObjectName("i4_7")
        self.gridLayout.addWidget(self.i4_7, 9, 5, 1, 1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 3, 0, 1, 3)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 3, 4, 1, 3)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 3, 8, 1, 3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 7, 3, 1)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 4, 7, 3, 1)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 8, 7, 3, 1)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 8, 3, 3, 1)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 4, 3, 3, 1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 3, 3, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.validate_bttn.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.validate_bttn)
        self.solve_bttn.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.solve_bttn)
        self.tipp_bttn.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.tipp_bttn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.MainWindow.setCentralWidget(self.centralwidget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 725, 21))
        self.menubar.setObjectName("menubar")
        self.menuHallo.setObjectName("menuHallo")
        self.MainWindow.setMenuBar(self.menubar)
        self.statusbar.setObjectName("statusbar")
        self.MainWindow.setStatusBar(self.statusbar)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave.setObjectName("actionSave")
        self.menuHallo.addAction(self.actionNew)
        self.menuHallo.addAction(self.actionOpen)
        self.menuHallo.addAction(self.actionSave)
        self.menubar.addAction(self.menuHallo.menuAction())
        self.solve_bttn.clicked.connect(self.solveButton)
        self.validate_bttn.clicked.connect(self.validateButton)
        self.tipp_bttn.clicked.connect(self.tippButton)
        self.actionOpen.triggered.connect(self.openFile)
        self.actionSave.triggered.connect(self.saveFile)
        self.actionNew.triggered.connect(self.newButton)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.validate_bttn.setText(_translate("MainWindow", "Validate"))
        self.solve_bttn.setText(_translate("MainWindow", "Solve"))
        self.tipp_bttn.setText(_translate("MainWindow", "Tipp"))
        self.menuHallo.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

    def newButton(self):
        self.label.setText("")
        for y in self.elements:
            for x in y:
                x.setText("")
                x.setStyleSheet("background-color:white")

    def saveFile(self):
        self.label.setText("")
        fname = QtWidgets.QFileDialog.getSaveFileName(self.MainWindow, 'Save File', 'c:\\', "Sudoku files (*.sudoku)")[0]
        if not fname:
            return
        with open(fname, "w") as f:
            su = self.translateTo2d()
            for e, y in enumerate(su):
                f.write("".join(list(map(str, y))).replace("None", "0") + "\n") if not e == 8 else f.write("".join(list(map(str, y))).replace("None", "0"))

    def openFile(self):
        self.label.setText("")
        pattern = re.compile(r"^(\d{9}\n){8}\d{9}\Z")
        fname = QtWidgets.QFileDialog.getOpenFileName(self.MainWindow, 'Open file', 'c:\\', "Sudoku files (*.sudoku)")[0]
        if not fname:
            return
        with open(fname, "r") as f:
            text = f.read()
            if pattern.search(text):
                l = [[x for x in y] for y in text.replace(" ", "").split("\n")]
                for y, y0 in zip(l, self.elements):
                    for x, x0 in zip(y, y0):
                        x0.setStyleSheet("background-color:white")
                        if not x == "0":
                            x0.setText(x)
                        elif x == "0":
                            x0.setText("")
            else:
                self.label.setText("Cannot load File - Filedata is corrupted")

    def tippButton(self):
        self.label.setText("")
        su = Sudoku(self.translateTo2d())
        if not su.isSolved():
            not_defined = su.getNotDefined()
            solution = su.solve()
            x, y = random.choice(not_defined)
            self.elements[y][x].setText(str(solution[y][x]))
            self.elements[y][x].setStyleSheet("background-color:lightgreen")

    def validateButton(self):
        self.label.setText("")
        su = Sudoku(self.translateTo2d())
        if su.isSolved():
            if su.validate():
                self.label.setText("Correct :) - There may be other solutions")
                return
        if su.validate():
            self.label.setText("So far so good, probably")
            return
        else:
            self.label.setText("Wrong :(")

    def solveButton(self):
        self.label.setText("")
        su = Sudoku(self.translateTo2d())
        not_defined = su.getNotDefined()
        su.solve()
        for ye, (y, y_i) in enumerate(zip(su.sudoku, self.elements)):
            for xe, (x, x_i) in enumerate(zip(y, y_i)):
                if not x:
                    self.label.setText("There is no solution - Invalid sudoku")
                    return
                x_i.setText(str(x))
                if (xe, ye) in not_defined:
                    x_i.setStyleSheet("background-color:lightblue")

    def translateTo2d(self):
        def translate(text):
            if text == "":
                return None
            return int(text)

        return [[translate(x.toPlainText().replace(" ", "")) for x in y] for y in self.elements]


def run():
    import sys

    app = QtWidgets.QApplication(sys.argv)
    UiMainWindow()
    sys.exit(app.exec_())
